package Interfaz;
import Logica.*;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;




public class InterfazUsuario extends javax.swing.JPanel {

    CardLayout cardLayout;
    CardLayout cardLayout2;
    CardLayout cardMensajes;
    
    public InterfazUsuario(){
        initComponents();
        
        cardLayout = (CardLayout)(PanelTarjetas.getLayout());
        cardLayout2 = (CardLayout)(CardsTipo.getLayout());
        cardMensajes = (CardLayout)(PanelMensaje.getLayout());
        
        cardLayout.addLayoutComponent(PanelMuestra, "PanelMuestra");
        cardLayout.addLayoutComponent(PanelIngreso, "PanelIngreso");
        
        cardLayout2.addLayoutComponent(CardAlumno, "CardAlumno");
        cardLayout2.addLayoutComponent(CardDocente, "CardDocente");
        cardLayout2.addLayoutComponent(CardNoDocente, "CardNoDocente");
        
        cardMensajes.addLayoutComponent(PanelConfirmacion, "PanelConfirmacion");
        cardMensajes.addLayoutComponent(PanelError, "PanelError");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        PanelMenuOpciones = new javax.swing.JPanel();
        LogoPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        BotonMuestra = new javax.swing.JButton();
        BotonIngreso = new javax.swing.JButton();
        PanelTarjetas = new javax.swing.JPanel();
        PanelMuestra = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMuestra = new javax.swing.JTable();
        PanelTipo1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ComboBoxTipoMuestra = new javax.swing.JComboBox<>();
        CheckBoxFiltroMuestra = new javax.swing.JCheckBox();
        BotonMuestraBorrar = new javax.swing.JButton();
        PanelIngreso = new javax.swing.JPanel();
        TituloIngreso = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelFormulario = new javax.swing.JPanel();
        PanelNombre = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        InputNombre = new javax.swing.JTextField();
        PanelApellido = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        InputApellido = new javax.swing.JTextField();
        PanelTipo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        CardsTipo = new javax.swing.JPanel();
        CardAlumno = new javax.swing.JPanel();
        PanelNombre1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        InputAlumnoSala = new javax.swing.JComboBox<>();
        PanelNombre2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        InputAlumnoEdad = new javax.swing.JComboBox<>();
        CardDocente = new javax.swing.JPanel();
        PanelNombre5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        InputDocenteSala = new javax.swing.JComboBox<>();
        PanelNombre6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        InputDocenteDireccion = new javax.swing.JTextField();
        CardNoDocente = new javax.swing.JPanel();
        PanelNombre7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        InputNoDocenteDireccion = new javax.swing.JTextField();
        PanelNombre8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        InputNoDocenteCategoria = new javax.swing.JComboBox<>();
        BotonGuardar = new javax.swing.JButton();
        PanelMensaje = new javax.swing.JPanel();
        PanelError = new javax.swing.JPanel();
        TextoError = new javax.swing.JTextArea();
        PanelConfirmacion = new javax.swing.JPanel();
        TextoConfirmacion = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(870, 500));

        jSplitPane1.setBackground(new java.awt.Color(51, 0, 102));
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setEnabled(false);

        PanelMenuOpciones.setBackground(new java.awt.Color(51, 0, 102));
        PanelMenuOpciones.setMinimumSize(new java.awt.Dimension(200, 110));
        PanelMenuOpciones.setPreferredSize(new java.awt.Dimension(200, 700));

        LogoPanel.setBackground(new java.awt.Color(255, 255, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("JARDIN \"SOL\"");

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel9)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        BotonMuestra.setText("Muestra");
        BotonMuestra.setPreferredSize(new java.awt.Dimension(170, 50));
        BotonMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMuestraActionPerformed(evt);
            }
        });

        BotonIngreso.setText("Ingreso");
        BotonIngreso.setPreferredSize(new java.awt.Dimension(170, 50));
        BotonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuOpcionesLayout = new javax.swing.GroupLayout(PanelMenuOpciones);
        PanelMenuOpciones.setLayout(PanelMenuOpcionesLayout);
        PanelMenuOpcionesLayout.setHorizontalGroup(
            PanelMenuOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuOpcionesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelMenuOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BotonMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        PanelMenuOpcionesLayout.setVerticalGroup(
            PanelMenuOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuOpcionesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(PanelMenuOpciones);

        PanelTarjetas.setBackground(new java.awt.Color(255, 255, 255));
        PanelTarjetas.setPreferredSize(new java.awt.Dimension(800, 700));
        PanelTarjetas.setLayout(new java.awt.CardLayout());

        PanelMuestra.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(771, 170));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(771, 170));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Muestra de personas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        TablaMuestra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaMuestra.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaMuestra);

        PanelTipo1.setBackground(new java.awt.Color(255, 255, 255));
        PanelTipo1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tipo de usuario");

        ComboBoxTipoMuestra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Docente", "No Docente" }));
        ComboBoxTipoMuestra.setSelectedItem(null);
        ComboBoxTipoMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoMuestraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTipo1Layout = new javax.swing.GroupLayout(PanelTipo1);
        PanelTipo1.setLayout(PanelTipo1Layout);
        PanelTipo1Layout.setHorizontalGroup(
            PanelTipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipo1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ComboBoxTipoMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTipo1Layout.setVerticalGroup(
            PanelTipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxTipoMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        CheckBoxFiltroMuestra.setText("Filtrar por sala");
        CheckBoxFiltroMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxFiltroMuestraActionPerformed(evt);
            }
        });

        BotonMuestraBorrar.setText("Borrar registro");
        BotonMuestraBorrar.setPreferredSize(new java.awt.Dimension(170, 50));
        BotonMuestraBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMuestraBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMuestraLayout = new javax.swing.GroupLayout(PanelMuestra);
        PanelMuestra.setLayout(PanelMuestraLayout);
        PanelMuestraLayout.setHorizontalGroup(
            PanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMuestraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMuestraLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelMuestraLayout.createSequentialGroup()
                        .addComponent(PanelTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckBoxFiltroMuestra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonMuestraBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addGroup(PanelMuestraLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelMuestraLayout.setVerticalGroup(
            PanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMuestraLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonMuestraBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CheckBoxFiltroMuestra)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        PanelTarjetas.add(PanelMuestra, "card3");

        PanelIngreso.setBackground(new java.awt.Color(255, 255, 255));

        TituloIngreso.setBackground(new java.awt.Color(51, 0, 102));
        TituloIngreso.setPreferredSize(new java.awt.Dimension(771, 170));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(771, 170));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingreso de personas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TituloIngresoLayout = new javax.swing.GroupLayout(TituloIngreso);
        TituloIngreso.setLayout(TituloIngresoLayout);
        TituloIngresoLayout.setHorizontalGroup(
            TituloIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloIngresoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        TituloIngresoLayout.setVerticalGroup(
            TituloIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloIngresoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        PanelFormulario.setBackground(new java.awt.Color(255, 255, 255));

        PanelNombre.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        InputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNombreLayout = new javax.swing.GroupLayout(PanelNombre);
        PanelNombre.setLayout(PanelNombreLayout);
        PanelNombreLayout.setHorizontalGroup(
            PanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(InputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNombreLayout.setVerticalGroup(
            PanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelApellido.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Apellido");

        javax.swing.GroupLayout PanelApellidoLayout = new javax.swing.GroupLayout(PanelApellido);
        PanelApellido.setLayout(PanelApellidoLayout);
        PanelApellidoLayout.setHorizontalGroup(
            PanelApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelApellidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(InputApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelApellidoLayout.setVerticalGroup(
            PanelApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelApellidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelTipo.setBackground(new java.awt.Color(255, 255, 255));
        PanelTipo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tipo de usuario");

        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Docente", "No Docente" }));
        ComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTipoLayout = new javax.swing.GroupLayout(PanelTipo);
        PanelTipo.setLayout(PanelTipoLayout);
        PanelTipoLayout.setHorizontalGroup(
            PanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipoLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTipoLayout.setVerticalGroup(
            PanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        CardsTipo.setLayout(new java.awt.CardLayout());

        CardAlumno.setBackground(new java.awt.Color(255, 255, 255));

        PanelNombre1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Salita");

        InputAlumnoSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salita de 1", "Salita de 2", "Salita de 3" }));
        InputAlumnoSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAlumnoSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNombre1Layout = new javax.swing.GroupLayout(PanelNombre1);
        PanelNombre1.setLayout(PanelNombre1Layout);
        PanelNombre1Layout.setHorizontalGroup(
            PanelNombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombre1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(InputAlumnoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        PanelNombre1Layout.setVerticalGroup(
            PanelNombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombre1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InputAlumnoSala, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelNombre2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Edad");

        InputAlumnoEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menos de 1 año", "1", "2", "3", "Mas de 3 años" }));
        InputAlumnoEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAlumnoEdadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNombre2Layout = new javax.swing.GroupLayout(PanelNombre2);
        PanelNombre2.setLayout(PanelNombre2Layout);
        PanelNombre2Layout.setHorizontalGroup(
            PanelNombre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombre2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputAlumnoEdad, 0, 200, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );
        PanelNombre2Layout.setVerticalGroup(
            PanelNombre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombre2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNombre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InputAlumnoEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CardAlumnoLayout = new javax.swing.GroupLayout(CardAlumno);
        CardAlumno.setLayout(CardAlumnoLayout);
        CardAlumnoLayout.setHorizontalGroup(
            CardAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardAlumnoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(PanelNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        CardAlumnoLayout.setVerticalGroup(
            CardAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardAlumnoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(CardAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        CardsTipo.add(CardAlumno, "card2");

        CardDocente.setBackground(new java.awt.Color(255, 255, 255));

        PanelNombre5.setBackground(new java.awt.Color(255, 255, 255));
        PanelNombre5.setPreferredSize(new java.awt.Dimension(328, 46));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Salita");

        InputDocenteSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salita de 1", "Salita de 2", "Salita de 3" }));
        InputDocenteSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDocenteSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNombre5Layout = new javax.swing.GroupLayout(PanelNombre5);
        PanelNombre5.setLayout(PanelNombre5Layout);
        PanelNombre5Layout.setHorizontalGroup(
            PanelNombre5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombre5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(InputDocenteSala, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        PanelNombre5Layout.setVerticalGroup(
            PanelNombre5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombre5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNombre5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(InputDocenteSala))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        PanelNombre6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Dirección");

        javax.swing.GroupLayout PanelNombre6Layout = new javax.swing.GroupLayout(PanelNombre6);
        PanelNombre6.setLayout(PanelNombre6Layout);
        PanelNombre6Layout.setHorizontalGroup(
            PanelNombre6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombre6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputDocenteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        PanelNombre6Layout.setVerticalGroup(
            PanelNombre6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombre6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNombre6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputDocenteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CardDocenteLayout = new javax.swing.GroupLayout(CardDocente);
        CardDocente.setLayout(CardDocenteLayout);
        CardDocenteLayout.setHorizontalGroup(
            CardDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardDocenteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(PanelNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(PanelNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CardDocenteLayout.setVerticalGroup(
            CardDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardDocenteLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(CardDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelNombre6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNombre5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        CardsTipo.add(CardDocente, "card3");

        CardNoDocente.setBackground(new java.awt.Color(255, 255, 255));

        PanelNombre7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Dirección");

        InputNoDocenteDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNoDocenteDireccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNombre7Layout = new javax.swing.GroupLayout(PanelNombre7);
        PanelNombre7.setLayout(PanelNombre7Layout);
        PanelNombre7Layout.setHorizontalGroup(
            PanelNombre7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombre7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputNoDocenteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        PanelNombre7Layout.setVerticalGroup(
            PanelNombre7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombre7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNombre7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNoDocenteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelNombre8.setBackground(new java.awt.Color(255, 255, 255));
        PanelNombre8.setPreferredSize(new java.awt.Dimension(328, 46));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Categoría");

        InputNoDocenteCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administración", "Maestranza" }));
        InputNoDocenteCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNoDocenteCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNombre8Layout = new javax.swing.GroupLayout(PanelNombre8);
        PanelNombre8.setLayout(PanelNombre8Layout);
        PanelNombre8Layout.setHorizontalGroup(
            PanelNombre8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombre8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputNoDocenteCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanelNombre8Layout.setVerticalGroup(
            PanelNombre8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombre8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNombre8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(InputNoDocenteCategoria))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CardNoDocenteLayout = new javax.swing.GroupLayout(CardNoDocente);
        CardNoDocente.setLayout(CardNoDocenteLayout);
        CardNoDocenteLayout.setHorizontalGroup(
            CardNoDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardNoDocenteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(PanelNombre8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(PanelNombre7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CardNoDocenteLayout.setVerticalGroup(
            CardNoDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardNoDocenteLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(CardNoDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelNombre7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNombre8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        CardsTipo.add(CardNoDocente, "card4");

        BotonGuardar.setText("Guardar registro");
        BotonGuardar.setPreferredSize(new java.awt.Dimension(170, 50));
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        PanelMensaje.setLayout(new java.awt.CardLayout());

        PanelError.setBackground(new java.awt.Color(255, 255, 255));

        TextoError.setColumns(20);
        TextoError.setRows(5);
        TextoError.setAutoscrolls(false);
        TextoError.setBorder(null);
        TextoError.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        TextoError.setEnabled(false);

        javax.swing.GroupLayout PanelErrorLayout = new javax.swing.GroupLayout(PanelError);
        PanelError.setLayout(PanelErrorLayout);
        PanelErrorLayout.setHorizontalGroup(
            PanelErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextoError, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelErrorLayout.setVerticalGroup(
            PanelErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextoError, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelMensaje.add(PanelError, "card3");

        PanelConfirmacion.setBackground(new java.awt.Color(255, 255, 255));

        TextoConfirmacion.setColumns(20);
        TextoConfirmacion.setRows(5);
        TextoConfirmacion.setAutoscrolls(false);
        TextoConfirmacion.setBorder(null);
        TextoConfirmacion.setDisabledTextColor(new java.awt.Color(0, 204, 0));
        TextoConfirmacion.setEnabled(false);

        javax.swing.GroupLayout PanelConfirmacionLayout = new javax.swing.GroupLayout(PanelConfirmacion);
        PanelConfirmacion.setLayout(PanelConfirmacionLayout);
        PanelConfirmacionLayout.setHorizontalGroup(
            PanelConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConfirmacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextoConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelConfirmacionLayout.setVerticalGroup(
            PanelConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConfirmacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextoConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelMensaje.add(PanelConfirmacion, "card4");

        javax.swing.GroupLayout PanelFormularioLayout = new javax.swing.GroupLayout(PanelFormulario);
        PanelFormulario.setLayout(PanelFormularioLayout);
        PanelFormularioLayout.setHorizontalGroup(
            PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormularioLayout.createSequentialGroup()
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardsTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFormularioLayout.createSequentialGroup()
                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PanelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PanelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addComponent(PanelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelFormularioLayout.createSequentialGroup()
                                .addComponent(PanelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(501, Short.MAX_VALUE))
        );
        PanelFormularioLayout.setVerticalGroup(
            PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormularioLayout.createSequentialGroup()
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(PanelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardsTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout PanelIngresoLayout = new javax.swing.GroupLayout(PanelIngreso);
        PanelIngreso.setLayout(PanelIngresoLayout);
        PanelIngresoLayout.setHorizontalGroup(
            PanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        PanelIngresoLayout.setVerticalGroup(
            PanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TituloIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelTarjetas.add(PanelIngreso, "card2");

        jSplitPane1.setRightComponent(PanelTarjetas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1298, 1298, 1298))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMuestraActionPerformed
        cardLayout.show(PanelTarjetas, "PanelMuestra");
    }//GEN-LAST:event_BotonMuestraActionPerformed

    private void BotonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresoActionPerformed
        cardLayout.show(PanelTarjetas, "PanelIngreso");
        
    }//GEN-LAST:event_BotonIngresoActionPerformed

    private void ComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoActionPerformed
        switch (ComboBoxTipo.getSelectedItem().toString()) {
            case "Alumno":
                cardLayout2.show(CardsTipo, "CardAlumno");
                break;
            case "Docente":
                cardLayout2.show(CardsTipo, "CardDocente");
                break;
            case "No Docente":
                cardLayout2.show(CardsTipo, "CardNoDocente");
        }
    }//GEN-LAST:event_ComboBoxTipoActionPerformed

    private void InputAlumnoSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAlumnoSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputAlumnoSalaActionPerformed

    private void InputAlumnoEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAlumnoEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputAlumnoEdadActionPerformed

    private void InputDocenteSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDocenteSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDocenteSalaActionPerformed

    private void InputNoDocenteCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNoDocenteCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNoDocenteCategoriaActionPerformed

    private void InputNoDocenteDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNoDocenteDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNoDocenteDireccionActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        //CONTROLES PARA EL FORMULARIO
        Administracion admin = new Administracion();
        
        int errores = 0;
        TextoError.setText("");
        String mensaje = "Errores:\n";
        String tipo = ComboBoxTipo.getSelectedItem().toString();
        String nombre = InputNombre.getText();
        String apellido = InputApellido.getText();
        String direccion = "";
        String sala= "";
        String edad = InputAlumnoEdad.getSelectedItem().toString();
        String categoria = InputNoDocenteCategoria.getSelectedItem().toString();
        
        
        //Control nombre
        if(nombre.length() <= 3){
            mensaje += "El nombre debe tener al menos 3 letras\n";
            errores++;
        }
        //Control apellido
        if(apellido.length() <= 3){
            mensaje += "El apellido debe tener al menos 3 letras\n";
            errores++;
        }
        //Control direccion
        switch(tipo){
            case "Alumno":
                sala = InputAlumnoSala.getSelectedItem().toString();
                break;
                
            case "Docente":
                sala = InputDocenteSala.getSelectedItem().toString();
                direccion = InputDocenteDireccion.getText();
                break;
                
            case "No Docente":
                direccion = InputNoDocenteDireccion.getText();
        }
        
        if(tipo != "Alumno"){
            if(direccion.length()<= 3){
                mensaje += "La dirección debe tener al menos 3 caracteres\n";
                errores++;
            }
        }
        
        if(errores==0){
            switch (tipo) {
                case "Alumno":
                    admin.agregarPersona(new Alumno(nombre, apellido, edad, sala));
                    break;
                case "Docente":
                    admin.agregarPersona(new Docente(nombre, apellido, direccion, sala));
                    break;
                case "No Docente":
                    admin.agregarPersona(new NoDocente(nombre, apellido, direccion, categoria));
                    
            }
            cardMensajes.show(PanelMensaje, "PanelConfirmacion");
            TextoConfirmacion.setText("La persona "+nombre+" "+apellido+" fue guardada");
        }else{
            cardMensajes.show(PanelMensaje, "PanelError");
            TextoError.setText(mensaje);
        }
        
        
        
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void ComboBoxTipoMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoMuestraActionPerformed
        Administracion admin = new Administracion();

        //Traer los datos del metodo getPersonas
        ArrayList<Persona> personas = admin.getPersonas(ComboBoxTipoMuestra.getSelectedItem().toString());

        //Obtener el modelo de la tabla para luego modificarla
        DefaultTableModel model = (DefaultTableModel) TablaMuestra.getModel();

        //Visibilidad de los filtros
        CheckBoxFiltroMuestra.setVisible(false);

        //Reseteo de columnas y filas
        model.setNumRows(0);
        model.setColumnCount(0);

        //Setteo de columnas según el tipo de usuario
        
        
        if(ComboBoxTipoMuestra.getSelectedItem().toString()!="Seleccionar"){
            model.addColumn("Nombre");
            model.addColumn("Apellido");
            switch(ComboBoxTipoMuestra.getSelectedItem().toString()){
                case "Alumno":
                    CheckBoxFiltroMuestra.setText("Filtrar por Sala");
                    model.addColumn("Edad");
                    model.addColumn("Sala");
                    break;
                case "Docente":
                    model.addColumn("Dirección");
                    model.addColumn("Sala");
                    CheckBoxFiltroMuestra.setText("Filtrar por Sala");
                    break;
                case "No Docente":
                    model.addColumn("Dirección");
                    model.addColumn("Categoría");
                    CheckBoxFiltroMuestra.setText("Filtrar por Categoría");
            }
        }
        CheckBoxFiltroMuestra.setVisible(true);

        //Inserción de datos
        for (Persona persona : personas) {
            String[] datos = new String[]{persona.getNombre(), persona.getApellido(), persona.getDato1(), persona.getDato2()};
            model.addRow(datos);
        }
    }//GEN-LAST:event_ComboBoxTipoMuestraActionPerformed

    private void CheckBoxFiltroMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxFiltroMuestraActionPerformed
        Administracion admin = new Administracion();
        CheckBoxFiltroMuestra.isSelected();
        if(CheckBoxFiltroMuestra.isSelected()){
            admin.ordenarPersonas(1);
        }else{
            admin.ordenarPersonas(0);
        }
        ComboBoxTipoMuestra.actionPerformed(evt);
        
    }//GEN-LAST:event_CheckBoxFiltroMuestraActionPerformed

    private void BotonMuestraBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMuestraBorrarActionPerformed
        Administracion admin = new Administracion();
        String[] datosPersonaEliminar = {ComboBoxTipoMuestra.getSelectedItem().toString(),"","","",""};

        if(TablaMuestra.getSelectedRow()==-1){
            System.out.println("Falta seleccionar una persona");
        }else{
            for(int i=1; i<5; i++){
                datosPersonaEliminar[i] = TablaMuestra.getModel().getValueAt(TablaMuestra.getSelectedRow(), i-1).toString();
            }
            try {
                System.out.println(datosPersonaEliminar[0] + " " + datosPersonaEliminar[1] + " " + datosPersonaEliminar[2] + " " + datosPersonaEliminar[3] + " " + datosPersonaEliminar[4]);
                if(admin.compararPersona(datosPersonaEliminar)==null){
                    System.out.println("No se encontró la persona a eliminar");
                }else{
                    admin.eliminarPersona(admin.compararPersona(datosPersonaEliminar));
                }
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
            ComboBoxTipoMuestra.actionPerformed(evt);
        }
    }//GEN-LAST:event_BotonMuestraBorrarActionPerformed

    private void InputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonIngreso;
    private javax.swing.JButton BotonMuestra;
    private javax.swing.JButton BotonMuestraBorrar;
    private javax.swing.JPanel CardAlumno;
    private javax.swing.JPanel CardDocente;
    private javax.swing.JPanel CardNoDocente;
    private javax.swing.JPanel CardsTipo;
    private javax.swing.JCheckBox CheckBoxFiltroMuestra;
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JComboBox<String> ComboBoxTipoMuestra;
    private javax.swing.JComboBox<String> InputAlumnoEdad;
    private javax.swing.JComboBox<String> InputAlumnoSala;
    private javax.swing.JTextField InputApellido;
    private javax.swing.JTextField InputDocenteDireccion;
    private javax.swing.JComboBox<String> InputDocenteSala;
    private javax.swing.JComboBox<String> InputNoDocenteCategoria;
    private javax.swing.JTextField InputNoDocenteDireccion;
    private javax.swing.JTextField InputNombre;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JPanel PanelApellido;
    private javax.swing.JPanel PanelConfirmacion;
    private javax.swing.JPanel PanelError;
    private javax.swing.JPanel PanelFormulario;
    private javax.swing.JPanel PanelIngreso;
    private javax.swing.JPanel PanelMensaje;
    private javax.swing.JPanel PanelMenuOpciones;
    private javax.swing.JPanel PanelMuestra;
    private javax.swing.JPanel PanelNombre;
    private javax.swing.JPanel PanelNombre1;
    private javax.swing.JPanel PanelNombre2;
    private javax.swing.JPanel PanelNombre5;
    private javax.swing.JPanel PanelNombre6;
    private javax.swing.JPanel PanelNombre7;
    private javax.swing.JPanel PanelNombre8;
    private javax.swing.JPanel PanelTarjetas;
    private javax.swing.JPanel PanelTipo;
    private javax.swing.JPanel PanelTipo1;
    private javax.swing.JTable TablaMuestra;
    private javax.swing.JTextArea TextoConfirmacion;
    private javax.swing.JTextArea TextoError;
    private javax.swing.JPanel TituloIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
