package Interfaz;
import Logica.*;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Principal extends javax.swing.JPanel {

    public Principal() {
        JOptionPane.showMessageDialog(null, "Bienvenido al JARDIN SOL!\nAprendamos Jugando...!");
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        PanelMuestra = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        PanelAlumno = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AlumnoEdad = new javax.swing.JSpinner();
        AlumnoSala = new javax.swing.JComboBox<>();
        PanelDocente = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        DocenteDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DocenteSala = new javax.swing.JComboBox<>();
        PanelNoDocente = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        NoDocenteDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        NoDocenteCategoria = new javax.swing.JComboBox<>();
        PanelPersona = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PersonaApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PersonaTipo = new javax.swing.JComboBox<>();
        PersonaNombre = new javax.swing.JTextField();
        BotonIngresoGuardas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TipoMuestra = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaMuestra = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        MuestraFiltroSala = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        BotonBorrar = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jInternalFrame1.setVisible(true);

        PanelAlumno.setVisible(false);

        jLabel4.setText("Sala:");

        jLabel5.setText("Edad:");

        AlumnoSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala 1", "Sala 2", "Sala 3" }));
        AlumnoSala.setSelectedItem(null);

        javax.swing.GroupLayout PanelAlumnoLayout = new javax.swing.GroupLayout(PanelAlumno);
        PanelAlumno.setLayout(PanelAlumnoLayout);
        PanelAlumnoLayout.setHorizontalGroup(
                PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAlumnoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                .addGap(91, 91, 91)
                                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AlumnoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AlumnoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(130, Short.MAX_VALUE))
        );

        PanelAlumnoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5});

        PanelAlumnoLayout.setVerticalGroup(
                PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAlumnoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AlumnoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AlumnoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelAlumnoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5});

        PanelDocente.setVisible(false);

        jLabel6.setText("Direccion:");

        DocenteDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocenteDireccionActionPerformed(evt);
            }
        });

        jLabel7.setText("Sala:");

        DocenteSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala 1", "Sala 2", "Sala 3" }));
        DocenteSala.setSelectedItem(null);

        javax.swing.GroupLayout PanelDocenteLayout = new javax.swing.GroupLayout(PanelDocente);
        PanelDocente.setLayout(PanelDocenteLayout);
        PanelDocenteLayout.setHorizontalGroup(
                PanelDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelDocenteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addGroup(PanelDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DocenteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DocenteSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        PanelDocenteLayout.setVerticalGroup(
                PanelDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelDocenteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DocenteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(DocenteSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelNoDocente.setVisible(false);

        jLabel8.setText("Direccion:");

        NoDocenteDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoDocenteDireccionActionPerformed(evt);
            }
        });

        jLabel9.setText("Categoria:");

        NoDocenteCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrativo", "Maestranza" }));
        NoDocenteCategoria.setSelectedItem(null);

        javax.swing.GroupLayout PanelNoDocenteLayout = new javax.swing.GroupLayout(PanelNoDocente);
        PanelNoDocente.setLayout(PanelNoDocenteLayout);
        PanelNoDocenteLayout.setHorizontalGroup(
                PanelNoDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelNoDocenteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelNoDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8))
                                .addGap(65, 65, 65)
                                .addGroup(PanelNoDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NoDocenteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NoDocenteCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(8, Short.MAX_VALUE))
        );
        PanelNoDocenteLayout.setVerticalGroup(
                PanelNoDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelNoDocenteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelNoDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NoDocenteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelNoDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(NoDocenteCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre: ");

        PersonaApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonaApellidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellido:");

        jLabel3.setText("Tipo de usuario: ");

        PersonaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Docente", "No docente" }));
        PersonaTipo.setSelectedItem(null);
        PersonaTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PersonaTipo.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                PersonaTipoComponentAdded(evt);
            }
        });
        PersonaTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonaTipoMouseClicked(evt);
            }
        });
        PersonaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonaTipoActionPerformed(evt);
            }
        });

        PersonaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonaNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPersonaLayout = new javax.swing.GroupLayout(PanelPersona);
        PanelPersona.setLayout(PanelPersonaLayout);
        PanelPersonaLayout.setHorizontalGroup(
                PanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelPersonaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PersonaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PersonaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PersonaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPersonaLayout.setVerticalGroup(
                PanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelPersonaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(PersonaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PersonaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PersonaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addContainerGap())
        );

        BotonIngresoGuardas.setText("Guardar");
        BotonIngresoGuardas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresoGuardasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BotonIngresoGuardas)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(PanelDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(PanelAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(PanelNoDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(PanelPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {PanelAlumno, PanelDocente});

        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(PanelPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelNoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(BotonIngresoGuardas)
                                .addGap(194, 194, 194))
        );

        PanelMuestra.addTab("Ingreso", jPanel1);

        jLabel10.setText("Tipo de usuario:");

        TipoMuestra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Docente", "No docente" }));
        TipoMuestra.setSelectedItem(null);
        TipoMuestra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TipoMuestra.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TipoMuestraComponentAdded(evt);
            }
        });
        TipoMuestra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TipoMuestraMouseClicked(evt);
            }
        });
        TipoMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoMuestraActionPerformed(evt);
            }
        });

        TablaMuestra.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
        ));
        TablaMuestra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMuestraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaMuestra);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 38, Short.MAX_VALUE)
        );

        MuestraFiltroSala.setText("Filtrar por sala");
        MuestraFiltroSala.setVisible(false);
        MuestraFiltroSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuestraFiltroSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 26, Short.MAX_VALUE)
        );

        BotonBorrar.setText("Borrar datos de la persona");
        BotonBorrar.setEnabled(false);
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addContainerGap())
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(TipoMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(MuestraFiltroSala)
                                                        .addGap(39, 39, 39)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(BotonBorrar)
                                                .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(TipoMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MuestraFiltroSala))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(147, 147, 147))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(153, 153, 153))))
        );

        PanelMuestra.addTab("Muestra", jPanel2);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelMuestra)
        );
        jInternalFrame1Layout.setVerticalGroup(
                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelMuestra)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jInternalFrame1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIngresoGuardasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresoGuardasActionPerformed
        // TODO add your handling code here:
        int sinerror = 0;
        Administracion admin = new Administracion();

        //Control de Tipo, Nombre, Apellido
        if ((PersonaTipo.getSelectedItem() == null) || ("".equals(PersonaNombre.getText())) || ("".equals(PersonaApellido.getText()))) {
            System.out.println("FALTA NOMBRE // APELLIDO // TIPO");

            //Control de los datos según el tipo, si no entra en el if, hace que la variable sinerror sea 1
        } else {
            switch (PersonaTipo.getSelectedItem().toString()) {
                case "Alumno":
                    if ((AlumnoSala.getSelectedItem() == null) || ((int) AlumnoEdad.getValue() == 0)) {
                        System.out.println("FALTAN DATOS DEL ALUMNO");      //HACER UNA EXCEPCION
                    } else {
                        sinerror = 1;
                    }
                    break;

                case "Docente":
                    if (("".equals(DocenteDireccion.getText())) || (DocenteSala.getSelectedItem() == null)) {
                        System.out.println("FALTAN DATOS DEL DOCENTE");      //HACER UNA EXCEPCION
                    } else {
                        sinerror = 1;
                    }
                    break;

                case "No docente":
                    if (("".equals(NoDocenteDireccion.getText())) || (NoDocenteCategoria.getSelectedItem() == null)) {
                        System.out.println("FALTAN DATOS DEL NO DOCENTE");      //HACER UNA EXCEPCION
                    } else {
                        sinerror = 1;
                    }
            }
        }

        if (sinerror == 1) {
            //Creo una instancia de persona según su tipo, y le envío los datos

            switch (PersonaTipo.getSelectedItem().toString()) {
                case "Alumno":
                    admin.agregarPersona(new Alumno(PersonaNombre.getText(), PersonaApellido.getText(), AlumnoSala.getSelectedItem().toString(), AlumnoEdad.getValue().toString()));
                    break;

                case "Docente":
                    admin.agregarPersona(new Docente(PersonaNombre.getText(), PersonaApellido.getText(), DocenteSala.getSelectedItem().toString(), DocenteDireccion.getText()));
                    break;

                case "No docente":
                    admin.agregarPersona(new NoDocente(PersonaNombre.getText(), PersonaApellido.getText(), NoDocenteCategoria.getSelectedItem().toString(), NoDocenteDireccion.getText()));
            }
        }
    }

    private void PersonaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonaNombreActionPerformed

    private void PersonaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonaTipoActionPerformed
        // Hacer todos los paneles invisibles
        PanelAlumno.setVisible(false);
        PanelDocente.setVisible(false);
        PanelNoDocente.setVisible(false);

        // Visibilizar el panel según el tipo
        switch(PersonaTipo.getSelectedItem().toString()){
            case "Alumno":
                PanelAlumno.setVisible(true);
                break;
            case "Docente":
                PanelDocente.setVisible(true);
                break;
            case "No docente":
                PanelNoDocente.setVisible(true);
                break;
        }

    }//GEN-LAST:event_PersonaTipoActionPerformed

    private void PersonaTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonaTipoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonaTipoMouseClicked

    private void PersonaTipoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_PersonaTipoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonaTipoComponentAdded

    private void PersonaApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonaApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonaApellidoActionPerformed

    private void NoDocenteDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoDocenteDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoDocenteDireccionActionPerformed

    private void DocenteDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocenteDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocenteDireccionActionPerformed

    private void TipoMuestraComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TipoMuestraComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoMuestraComponentAdded

    private void TipoMuestraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TipoMuestraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoMuestraMouseClicked

    private void TipoMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoMuestraActionPerformed
        Administracion admin = new Administracion();

        //Traer los datos del metodo getPersonas
        ArrayList<Persona> personas = admin.getPersonas(TipoMuestra.getSelectedItem().toString());

        //Obtener el modelo de la tabla para luego modificarla
        DefaultTableModel model = (DefaultTableModel) TablaMuestra.getModel();

        //Visibilidad de los filtros
        MuestraFiltroSala.setVisible(false);



        //Reseteo de columnas y filas
        model.setNumRows(0);
        model.setColumnCount(0);

        //Setteo de columnas según el tipo de usuario
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        switch(TipoMuestra.getSelectedItem().toString()){
            case "Alumno":
                MuestraFiltroSala.setText("Filtrar por Sala");
                model.addColumn("Sala");
                model.addColumn("Edad");
                break;
            case "Docente":
                model.addColumn("Sala");
                model.addColumn("Dirección");
                MuestraFiltroSala.setText("Filtrar por Sala");
                break;
            case "No docente":
                model.addColumn("Categoría");
                model.addColumn("Dirección");
                MuestraFiltroSala.setText("Filtrar por Categoría");
        }

        MuestraFiltroSala.setVisible(true);

        //Inserción de datos
        for (Persona persona : personas) {
            String[] datos = new String[]{persona.getNombre(), persona.getApellido(), persona.getDato1(), persona.getDato2()};
            model.addRow(datos);
        }

    }//GEN-LAST:event_TipoMuestraActionPerformed

    private void MuestraFiltroSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuestraFiltroSalaActionPerformed
        // TODO add your handling code here:
        Administracion admin = new Administracion();
        MuestraFiltroSala.isSelected();
        if(MuestraFiltroSala.isSelected()){
            admin.ordenarPersonas(1);
        }else{
            admin.ordenarPersonas(0);
        }
        TipoMuestra.actionPerformed(evt);
    }//GEN-LAST:event_MuestraFiltroSalaActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        // TODO add your handling code here:
        Administracion admin = new Administracion();
        String[] datosPersonaEliminar = {TipoMuestra.getSelectedItem().toString(),"","","",""};

        if(TablaMuestra.getSelectedRow()==-1){
            System.out.println("Falta seleccionar una persona");

        }else{
            for(int i=1; i<5; i++){
                datosPersonaEliminar[i] = TablaMuestra.getModel().getValueAt(TablaMuestra.getSelectedRow(), i-1).toString();
            }
            try {
                System.out.println(datosPersonaEliminar[0] + " " + datosPersonaEliminar[1] + " " + datosPersonaEliminar[2] + " " + datosPersonaEliminar[3] + " " + datosPersonaEliminar[4]);
                if(admin.compararPersona(datosPersonaEliminar)==null){
                    System.out.println("No se encontró la persona a eliminar");
                }else{
                    admin.eliminarPersona(admin.compararPersona(datosPersonaEliminar));
                }
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
            TipoMuestra.actionPerformed(evt);
        }
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void TablaMuestraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMuestraMouseClicked
        // TODO add your handling code here:
        BotonBorrar.setEnabled(true);
    }//GEN-LAST:event_TablaMuestraMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AlumnoEdad;
    private javax.swing.JComboBox<String> AlumnoSala;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonIngresoGuardas;
    private javax.swing.JTextField DocenteDireccion;
    private javax.swing.JComboBox<String> DocenteSala;
    private javax.swing.JCheckBox MuestraFiltroSala;
    private javax.swing.JComboBox<String> NoDocenteCategoria;
    private javax.swing.JTextField NoDocenteDireccion;
    private javax.swing.JPanel PanelAlumno;
    private javax.swing.JPanel PanelDocente;
    private javax.swing.JTabbedPane PanelMuestra;
    private javax.swing.JPanel PanelNoDocente;
    private javax.swing.JPanel PanelPersona;
    private javax.swing.JTextField PersonaApellido;
    private javax.swing.JTextField PersonaNombre;
    private javax.swing.JComboBox<String> PersonaTipo;
    private javax.swing.JTable TablaMuestra;
    private javax.swing.JComboBox<String> TipoMuestra;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
